# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0002_auto_20180513_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AddField(
            model_name='quantity',
            name='id_quant',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='id_cart',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
