# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0004_itembill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
