# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_bill_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='shopping_cart',
        ),
    ]
