# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0006_remove_bill_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(upload_to='ykea/static/ykea/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(upload_to='ykea/static/ykea/files/'),
        ),
    ]
