# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0007_auto_20180516_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(upload_to='ykea/static/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(upload_to='ykea/static/files/'),
        ),
    ]
