# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0011_auto_20180516_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured_photo',
            field=models.ImageField(default='ykea/static/images/default.jpg', upload_to='ykea/static/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.FileField(default='ykea/static/files/default.pdf', upload_to='ykea/static/files/'),
        ),
    ]
