# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0013_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='item_list',
            field=models.ManyToManyField(blank=True, default=None, null=True, through='ykea.Quantity', to='ykea.Item'),
        ),
    ]
